import logging
from datetime import datetime
from typing import Dict, List
from jinja2 import Template

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """
# {{ title }}
**Date:** {{ date }}

## Executive Summary
{{ executive_summary }}

## Table of Contents
{% for section in sections.keys() %}
- [{{ section }}](#{{ section|lower|replace(' ', '-') }})
{% endfor %}

---

{% for title, content in sections.items() %}
## {{ title }}
{{ content }}

---
{% endfor %}

## Source Citations
{% for source in sources %}
- {{ source }}
{% endfor %}

---
**Disclaimer:** *This report is generated by an AI agent for research purposes only. Not financial advice.*
"""

async def generate_report(template_name: str, sections: Dict[str, str], sources: List[str]) -> str:
    """
    Generates a markdown report using Jinja2.
    """
    try:
        title_map = {
            "company_profile": "Company Profile Report",
            "earnings_analysis": "Earnings Analysis Report",
            "risk_assessment": "Risk Assessment Report",
            "industry_comparison": "Industry Comparison Report",
            "investment_report": "Investment Research Report"
        }
        
        title = title_map.get(template_name, "Financial Research Report")
        
        # Auto-generate executive summary from first section if not provided
        exec_summary = sections.get("Executive Summary")
        if not exec_summary and sections:
            first_val = list(sections.values())[0]
            exec_summary = first_val[:500] + "..." if len(first_val) > 500 else first_val

        template = Template(REPORT_TEMPLATE)
        markdown = template.render(
            title=title,
            date=datetime.now().strftime("%Y-%m-%d"),
            executive_summary=exec_summary,
            sections=sections,
            sources=sources
        )
        
        return markdown
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        return "# Error\nReport generation failed."
